// Shared restaurant data
export const restaurantData: Record<string, any> = {
  'rest-1': {
    id: 'rest-1',
    name: 'The Golden Fork',
    description: 'Award-winning fine dining restaurant serving contemporary French cuisine with a modern twist.',
    fullDescription: 'The Golden Fork is a culinary gem in the heart of Dubai Marina, offering an exquisite dining experience that combines French culinary traditions with innovative contemporary techniques. Our Michelin-starred chef creates seasonal menus featuring the finest ingredients sourced from around the world. The elegant ambiance, attentive service, and stunning marina views make this the perfect destination for special occasions, romantic dinners, or business dining.',
    cuisine: 'French',
    location: 'Dubai Marina',
    address: '123 Marina Walk, Dubai Marina, Dubai',
    priceRange: '$$$$',
    priceInr: 3500,
    rating: 4.9,
    reviewCount: 1245,
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=800&fit=crop',
    ],
    features: ['Reservations', 'Outdoor Seating', 'Vegetarian Options', 'Parking', 'WiFi', 'Live Music'],
    tags: ['Fine Dining', 'Romantic', 'Award Winner'],
    openTime: '6:00 PM',
    closeTime: '11:00 PM',
    hours: {
      monday: { open: '6:00 PM', close: '11:00 PM' },
      tuesday: { open: '6:00 PM', close: '11:00 PM' },
      wednesday: { open: '6:00 PM', close: '11:00 PM' },
      thursday: { open: '6:00 PM', close: '11:00 PM' },
      friday: { open: '6:00 PM', close: '12:00 AM' },
      saturday: { open: '6:00 PM', close: '12:00 AM' },
      sunday: { open: '6:00 PM', close: '11:00 PM' },
    },
    reservationsAvailable: true,
    outdoorSeating: true,
    vegetarianOptions: true,
    phone: '+971 4 123 4567',
    menu: {
      appetizers: [
        { name: 'Foie Gras', description: 'Pan-seared foie gras with fig compote', price: 450 },
        { name: 'Escargot', description: 'Traditional French snails with garlic butter', price: 380 },
        { name: 'Truffle Arancini', description: 'Crispy risotto balls with black truffle', price: 420 },
      ],
      mains: [
        { name: 'Duck Confit', description: 'Slow-cooked duck leg with orange sauce', price: 680 },
        { name: 'Beef Wellington', description: 'Prime beef wrapped in puff pastry', price: 850 },
        { name: 'Lobster Thermidor', description: 'Fresh lobster in creamy white wine sauce', price: 920 },
        { name: 'Vegetarian Wellington', description: 'Mushroom and vegetable wellington', price: 580 },
      ],
      desserts: [
        { name: 'Crème Brûlée', description: 'Classic French vanilla custard', price: 280 },
        { name: 'Chocolate Soufflé', description: 'Warm chocolate soufflé with vanilla ice cream', price: 320 },
        { name: 'Tarte Tatin', description: 'Upside-down apple tart', price: 260 },
      ],
    },
    reviews: [
      {
        id: 1,
        name: 'Michael Chen',
        rating: 5,
        date: '2025-10-20',
        comment: 'Absolutely exceptional dining experience! The service was impeccable, and every dish was a masterpiece. The beef Wellington was perfectly cooked, and the wine pairing was excellent. Highly recommend for special occasions!',
        helpful: 89,
      },
      {
        id: 2,
        name: 'Sophie Laurent',
        rating: 5,
        date: '2025-10-15',
        comment: 'The best French restaurant in Dubai! The ambiance is elegant, the staff is knowledgeable, and the food is outstanding. The duck confit was tender and flavorful. Worth every dirham!',
        helpful: 67,
      },
      {
        id: 3,
        name: 'David Thompson',
        rating: 4,
        date: '2025-10-10',
        comment: 'Great restaurant with excellent food quality. The service was attentive, though a bit slow during peak hours. The lobster thermidor was delicious. Overall a wonderful experience.',
        helpful: 45,
      },
    ],
  },
  'rest-2': {
    id: 'rest-2',
    name: 'Spice Garden',
    description: 'Authentic Indian cuisine with a vibrant atmosphere.',
    fullDescription: 'Spice Garden brings the authentic flavors of India to the heart of Dubai. Our chefs use traditional recipes passed down through generations, combined with the finest spices imported directly from India. The vibrant atmosphere, warm hospitality, and extensive menu make it perfect for families, groups, or anyone craving authentic Indian cuisine.',
    cuisine: 'Indian',
    location: 'Downtown Dubai',
    address: '456 Sheikh Zayed Road, Downtown Dubai',
    priceRange: '$$',
    priceInr: 1200,
    rating: 4.7,
    reviewCount: 892,
    images: [
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&h=800&fit=crop',
    ],
    features: ['Family Friendly', 'Vegetarian Options', 'Takeout'],
    tags: ['Authentic', 'Family Friendly', 'Popular'],
    openTime: '12:00 PM',
    closeTime: '11:00 PM',
    hours: {
      monday: { open: '12:00 PM', close: '11:00 PM' },
      tuesday: { open: '12:00 PM', close: '11:00 PM' },
      wednesday: { open: '12:00 PM', close: '11:00 PM' },
      thursday: { open: '12:00 PM', close: '11:00 PM' },
      friday: { open: '12:00 PM', close: '11:00 PM' },
      saturday: { open: '12:00 PM', close: '11:00 PM' },
      sunday: { open: '12:00 PM', close: '11:00 PM' },
    },
    reservationsAvailable: true,
    outdoorSeating: false,
    vegetarianOptions: true,
    phone: '+971 4 234 5678',
    menu: {
      appetizers: [
        { name: 'Samosas', description: 'Crispy fried pastries with spiced potatoes', price: 45 },
        { name: 'Paneer Tikka', description: 'Grilled cottage cheese with spices', price: 65 },
      ],
      mains: [
        { name: 'Butter Chicken', description: 'Creamy tomato-based curry', price: 85 },
        { name: 'Biryani', description: 'Fragrant basmati rice with meat', price: 95 },
      ],
      desserts: [
        { name: 'Gulab Jamun', description: 'Sweet milk dumplings in syrup', price: 35 },
      ],
    },
    reviews: [],
  },
  'rest-3': {
    id: 'rest-3',
    name: 'Sakura Sushi Bar',
    description: 'Premium Japanese restaurant specializing in fresh sushi and sashimi.',
    fullDescription: 'Sakura Sushi Bar offers an authentic Japanese dining experience with fresh, premium ingredients flown in daily from Japan. Our master sushi chefs create artful presentations of traditional and modern Japanese cuisine in a serene, minimalist setting.',
    cuisine: 'Japanese',
    location: 'Palm Jumeirah',
    address: '789 Palm Boulevard, Palm Jumeirah',
    priceRange: '$$$',
    priceInr: 2800,
    rating: 4.8,
    reviewCount: 1567,
    images: [
      'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&h=800&fit=crop',
    ],
    features: ['Reservations', 'Outdoor Seating', 'Parking', 'Live Music'],
    tags: ['Sushi', 'Premium', 'Trendy'],
    openTime: '5:00 PM',
    closeTime: '12:00 AM',
    hours: {
      monday: { open: '5:00 PM', close: '12:00 AM' },
      tuesday: { open: '5:00 PM', close: '12:00 AM' },
      wednesday: { open: '5:00 PM', close: '12:00 AM' },
      thursday: { open: '5:00 PM', close: '12:00 AM' },
      friday: { open: '5:00 PM', close: '12:00 AM' },
      saturday: { open: '5:00 PM', close: '12:00 AM' },
      sunday: { open: '5:00 PM', close: '12:00 AM' },
    },
    reservationsAvailable: true,
    outdoorSeating: true,
    vegetarianOptions: false,
    phone: '+971 4 345 6789',
    menu: {
      appetizers: [],
      mains: [],
      desserts: [],
    },
    reviews: [],
  },
  'rest-4': {
    id: 'rest-4',
    name: 'Mediterranean Breeze',
    description: 'Casual beachfront restaurant serving fresh Mediterranean cuisine.',
    fullDescription: 'Mediterranean Breeze offers a relaxed beachfront dining experience with fresh, healthy Mediterranean dishes. Enjoy stunning ocean views while savoring authentic flavors from Greece, Italy, and Spain.',
    cuisine: 'Mediterranean',
    location: 'JBR Beach',
    address: '321 Beach Walk, JBR',
    priceRange: '$$',
    priceInr: 1500,
    rating: 4.6,
    reviewCount: 2341,
    images: [
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=800&fit=crop',
    ],
    features: ['Outdoor Seating', 'Beachfront', 'Vegetarian Options', 'Parking'],
    tags: ['Beachfront', 'Casual', 'Popular'],
    openTime: '11:00 AM',
    closeTime: '11:00 PM',
    hours: {
      monday: { open: '11:00 AM', close: '11:00 PM' },
      tuesday: { open: '11:00 AM', close: '11:00 PM' },
      wednesday: { open: '11:00 AM', close: '11:00 PM' },
      thursday: { open: '11:00 AM', close: '11:00 PM' },
      friday: { open: '11:00 AM', close: '11:00 PM' },
      saturday: { open: '11:00 AM', close: '11:00 PM' },
      sunday: { open: '11:00 AM', close: '11:00 PM' },
    },
    reservationsAvailable: false,
    outdoorSeating: true,
    vegetarianOptions: true,
    phone: '+971 4 456 7890',
    menu: {
      appetizers: [],
      mains: [],
      desserts: [],
    },
    reviews: [],
  },
  'rest-5': {
    id: 'rest-5',
    name: 'BBQ Smokehouse',
    description: 'Authentic American barbecue with slow-smoked meats.',
    fullDescription: 'BBQ Smokehouse brings authentic American barbecue to Dubai. Our meats are slow-smoked for hours using traditional methods, resulting in tender, flavorful dishes that pair perfectly with our craft beer selection.',
    cuisine: 'American',
    location: 'Dubai Sports City',
    address: '567 Sports Avenue, Sports City',
    priceRange: '$$',
    priceInr: 1800,
    rating: 4.5,
    reviewCount: 678,
    images: [
      'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&h=800&fit=crop',
    ],
    features: ['Sports Bar', 'Parking', 'Takeout', 'Live Sports'],
    tags: ['BBQ', 'Sports Bar', 'Casual'],
    openTime: '12:00 PM',
    closeTime: '1:00 AM',
    hours: {
      monday: { open: '12:00 PM', close: '1:00 AM' },
      tuesday: { open: '12:00 PM', close: '1:00 AM' },
      wednesday: { open: '12:00 PM', close: '1:00 AM' },
      thursday: { open: '12:00 PM', close: '1:00 AM' },
      friday: { open: '12:00 PM', close: '1:00 AM' },
      saturday: { open: '12:00 PM', close: '1:00 AM' },
      sunday: { open: '12:00 PM', close: '1:00 AM' },
    },
    reservationsAvailable: false,
    outdoorSeating: false,
    vegetarianOptions: false,
    phone: '+971 4 567 8901',
    menu: {
      appetizers: [],
      mains: [],
      desserts: [],
    },
    reviews: [],
  },
  'rest-6': {
    id: 'rest-6',
    name: 'La Dolce Vita',
    description: 'Charming Italian trattoria serving authentic pasta, pizza, and Italian classics.',
    fullDescription: 'La Dolce Vita captures the essence of Italian dining with authentic recipes from nonnas across Italy. Our warm, rustic atmosphere and traditional dishes create an unforgettable Italian dining experience.',
    cuisine: 'Italian',
    location: 'Dubai Marina',
    address: '890 Marina Promenade, Dubai Marina',
    priceRange: '$$$',
    priceInr: 2200,
    rating: 4.7,
    reviewCount: 1123,
    images: [
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&h=800&fit=crop',
    ],
    features: ['Reservations', 'Outdoor Seating', 'Vegetarian Options', 'Family Friendly'],
    tags: ['Authentic', 'Family Friendly', 'Romantic'],
    openTime: '12:00 PM',
    closeTime: '11:00 PM',
    hours: {
      monday: { open: '12:00 PM', close: '11:00 PM' },
      tuesday: { open: '12:00 PM', close: '11:00 PM' },
      wednesday: { open: '12:00 PM', close: '11:00 PM' },
      thursday: { open: '12:00 PM', close: '11:00 PM' },
      friday: { open: '12:00 PM', close: '11:00 PM' },
      saturday: { open: '12:00 PM', close: '11:00 PM' },
      sunday: { open: '12:00 PM', close: '11:00 PM' },
    },
    reservationsAvailable: true,
    outdoorSeating: true,
    vegetarianOptions: true,
    phone: '+971 4 678 9012',
    menu: {
      appetizers: [],
      mains: [],
      desserts: [],
    },
    reviews: [],
  },
};

export function getRestaurantById(id: string) {
  return restaurantData[id] || null;
}

